yd/yd/urls.py
from django.contrib import admin
from django.urls import path,include
# from youtube_downloader import urls
# from youtube_downloader import views


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('youtube_downloader.urls')),
]

yd/youtube_downloader/urls.py
from django.urls import path
from . import views

app_name = 'ytd'
urlpatterns = [
    path('', views.index, name='index'),
    path('download/', views.yt_download, name='yt_download'),
    path('download_complete/<itag>', views.download_complete, name='download_complete'),
    # path('download_complete/<itag>', views.download_complete, name='download_complete'),
    path('download_2/', views.yt_download2, name='yt_download_2')

]

yd/youtube_downloader/models.py
from django.db import models

# Create your models here.

yd/youtube_downloader/forms.py
from django import forms


def get_video():
    pass

class IndexForm(forms.Form):
    url = forms.URLField()
 

yd/youtube_downloader/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import FormView
from .forms import IndexForm
from django.urls import reverse_lazy
from pytube import YouTube
from pytube.extract import video_id
from django.http import FileResponse
import os

url = ''

# функция главной страницы
def index(request):
    return render(request, 'index.html')

# завершение загрузки
def download_complete(request, itag):
    global url
    # return render(request, 'download_complete.html', context={'res': resolution})
    # 
    # для варианта №1
    # homedir = os.path.expanduser('~')
    # dirs = homedir + '/Downloads'
    # print(f'DIRECT:', f'{dirs}/Downloads')
    # 
    if request.method == 'POST':
        # 
        # варинат №1 не работает на боевом - сохраняет файл на сервере
        # YouTube(url).streams.get_by_resolution(resolution).download(homedir+'/Downloads')
        # 
        # рабочий вариант №2 - свойство as_attachment позволяет сохранить как приложение, но предварительно сохраняет на сервере
        try:
            # return FileResponse(open(YouTube(url).streams.get_by_resolution(resolution).download(skip_existing=True),'rb'), as_attachment=True)
            return FileResponse(open(YouTube(url).streams.get_by_itag(itag).download(skip_existing=True),'rb'), as_attachment=True)
        except Exception as err:
            print(err)
            return render(request, 'sorry.html', {'err': err})
        # рабочий вариант №2 - но по itag
        # return FileResponse(open(YouTube(url).streams.get_by_itag(int(itag)).download(skip_existing=True),'rb'), as_attachment=True)
    else:
        return render(request, 'sorry.html')

# сбор информации со streams
def yt_download(request):
    global url
    url = request.GET.get('url')
    url = f'https://youtube.com/embed/{video_id(url)}'
    try:
        obj = YouTube(url)
        resolutions = []
        # только видео формат
        strm_all = obj.streams.filter(progressive=True, file_extension='mp4')

        for i in strm_all:
            resolutions.append(i.resolution)
        # 
        # способ убрать дубликаты из списка - в словарь с ключами из списка и обратно в список
        resolutions = list(dict.fromkeys(resolutions))
        # 
        embed_link = f'https://youtube.com/embed/{video_id(url)}'
        return render(request, 'yt_download.html', context={'resolutions': resolutions, 'url': url, 'embed_link': embed_link})

    except:
        return render(request, 'sorry.html')


def yt_download2(request):
    global url
    url = request.GET.get('url')
    url = f'https://youtube.com/embed/{video_id(url)}'
    try:

        obj = YouTube(url)
        
        # только видео формат
        strm_v = obj.streams.filter(progressive=True, file_extension='mp4')
        strm_v_out = {}
        strm_a_out = {}
        for v in strm_v:
            size = str(round(obj.streams.get_by_itag(v.itag).filesize_approx / (1024**2)))
            strm_v_out.update({v.itag: {'resolution': v.resolution, 'size': size}})
        print('strm_v_out', strm_v_out)
        
        # только аудио формат
        strm_a = obj.streams.filter(type='audio')
        for a in strm_a:
            size = str(round(obj.streams.get_by_itag(a.itag).filesize_approx / (1024**2)))
            strm_a_out.update({a.itag: {'format': a.mime_type, 'size': size}})
        print('strm_a_out', strm_a_out)

        # 
        # способ убрать дубликаты из списка - в словарь с ключами из списка и обратно в список
        # resolutions = list(dict.fromkeys(resolutions))
        # 
        embed_link = f'https://youtube.com/embed/{video_id(url)}'
        return render(request, 'yt_download2.html', context={'strm_v_out': strm_v_out, 'strm_a_out': strm_a_out, 'url': url, 'embed_link': embed_link})

    except Exception as err:
        print(err)
        return render(request, 'sorry.html', {'err': err})


# def get_stream(url):
#     yt = YouTube(url).streams
#     return yt


# class GetVideo(FormView):
#     template_name = 'index.html'
#     form_class = IndexForm
#     success_url = reverse_lazy('index')

yd/youtube_downloader/templates/download_complete.html
download_complete

yd/youtube_downloader/templates/index.html
<!doctype html>
<html lang="en">

<head>
  <title>Youtube Downloader</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
  {# navbar #}
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="{% url 'ytd:index' %}">Download video from YouTube</a>
    <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> -->

    <!-- <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="#">Facebook Photo/Video Download <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Instagram Photo/Video Download</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Whatsapp Status Download</a>
        </li>

      </ul>

    </div> -->
  </nav>



  {# navbar end #}
  <div class="container">
  {% block container %}
    <br>
    <center><h1>ENTER YOTUBE LINK HERE</h1></center>
    <!-- form start -->
    <form action="{% url 'ytd:yt_download_2' %}" method='get'>
      <br>
      <div class="form-group">

        <input name="url" type="text" class="form-control" id="link" aria-describedby="emailHelp" placeholder="Enter Your Selected Youtube Video Link">
        <small id="emailHelp" class="form-text text-muted"></small>
      </div>
      <br>
      <center>
      <button type="submit" class="btn btn-primary">Submit</button>
    </center>
    </form>
    <!-- form end -->
  {% endblock %}
  </div>

 


  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"></script>
</body>

</html>

yd/youtube_downloader/templates/sorry.html
<h1>Sorry</h1>
<p>{{ err }}</p>

yd/youtube_downloader/templates/yt_download.html
{% extends 'index.html' %}
{% block container %}
<br>
<center>
    <h2>Your video</h2>
</center>
<center>
    <div class="embed-responsive embed-responsive-16by9">
        <iframe width="560" height="315"  class="embed-responsive-item" src="{{ embed_link }}" allowfullscreen></iframe>

    </div>
</center>
<br>
<p>Url = {{ url }}</p>
<p>Embed_link = {{ embed_link }}</p>
<table class="table">
    <thead class="thead-dark">
        <tr>

            <th scope="col">Select Resolution</th>
            <th scope="col">Download</th>
        </tr>


    </thead>
    <tbody>
        {% for resolution in resolutions %}
        <tr>

            <td>{{ resolution }}</td>
            <td>
                <form action="{% url 'ytd:download_complete' resolution %}" method="POST" class="post-form">
                    {% csrf_token %}
                    <input type="submit" class="btn btn-success" value="DOWNLOAD">
                </form>
            </td>
        </tr>
        {% endfor %}

    </tbody>
</table>
{% endblock %}

yd/youtube_downloader/templates/yt_download2.html
{% extends 'index.html' %}
{% block container %}
<br>
<center>
    <h2>Your video</h2>
</center>
<center>
        <iframe width="560" height="315" src="{{ url }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</center>
<br>


<div class="container">
    <div class="row">
        <div class="col">
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Select Resolution</th>
                        <th scope="col">Size</th>
                        <!-- <th scope="col">Itag</th> -->
                        <th scope="col">Download</th>
                    </tr>
                </thead>
                <tbody>
                    {% for itag, value in strm_v_out.items %}
                    <tr>
                        <td>{{ value.resolution  }}</td>
                        <td>{{ value.size }}</td>
                        <!-- <td>{{ itag }}</td> -->
                        <td>
                            <form action="{% url 'ytd:download_complete' itag %}" method="POST"
                                class="post-form">
                                {% csrf_token %}
                                <input type="submit" class="btn btn-success" value="DOWNLOAD">
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col">
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Type</th>
                        <th scope="col">Size</th>
                        <!-- <th scope="col">Itag</th> -->
                        <th scope="col">Download</th>
                    </tr>
                </thead>
                <tbody>
                    {% for itag, value in strm_a_out.items %}
                    <tr>
                        <td>{{ value.format  }}</td>
                        <td>{{ value.size }}</td>
                        <!-- <td>{{ itag }}</td> -->
                        <td>
                            <form action="{% url 'ytd:download_complete' itag %}" method="POST"
                                class="post-form">
                                {% csrf_token %}
                                <input type="submit" class="btn btn-success" value="DOWNLOAD">
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="w-100"></div>
    </div>
</div>
{% endblock %}